In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
# 1차원 배열
a1 = np.array([1,2,3])

# 2차원 배열
a2 = np.array([[1,2,3],[4,5,6]])

# 3차원 배열
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
a1.shape
a2.shape
a3.shape 

(2, 2, 2)

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)   

[5 7 9]


In [12]:
a*b

array([ 4, 10, 18])

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a + b)
print(a * b) 

[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]


In [17]:
a = np.array([1,2,3])
np.sum(a) 

6

In [18]:
np.min(a)

1

In [19]:
np.max (a)

3

In [20]:
np.mean(a)

2.0

In [111]:
a = np.array([1,2,3],[4,5,6])
np.sum(a)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [26]:
np.min(a)

1

In [27]:
np.max(a)

3

In [28]:
np.mean(a)

2.0

In [29]:
np.mean(arr, axis=1) # 행 별 평균

NameError: name 'arr' is not defined

In [112]:
np.mean(arr, axis=0) # 열 별 평균

NameError: name 'arr' is not defined

In [114]:
a = np.array([1, 2, 3, 4, 5])
a[0] # list indexing과 동일

1

In [116]:
a[2]

3

In [117]:
a[1:4]

array([2, 3, 4])

In [118]:
a[:3] 

array([1, 2, 3])

In [119]:
a[3:] 

array([4, 5])

In [120]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.reshape((2, 3))  # [[1, 2, 3], [4, 5, 6]]
a.T  # 행렬의 전치 : [[1, 3, 5], [2, 4, 6]] 

array([[1, 3, 5],
       [2, 4, 6]])

In [121]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))  # 단순 병합 : [1, 2, 3, 4, 5, 6]

array([1, 2, 3, 4, 5, 6])

In [122]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)

In [123]:
a = np.array([1, 2, 3, 4, 5, 6])
b, c = np.split(a, [3])  # 배열 분리 : [1, 2, 3], [4, 5, 6]

In [124]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b, c = np.split(a, [1], axis=0)  # [[1, 2, 3]], [[4, 5, 6]]

In [127]:
# list > DataFrame
data = [['a',10],['b',20],['c',30]]
df = pd.DataFrame(data, columns=['name', 'age'])
print(df)

NameError: name 'pd' is not defined

In [128]:
# dictionary > DataFrame
data = {'name':['a','b','c'],'age':[10,20,30]}
df = pd.DataFrame(data)
print(df)

NameError: name 'pd' is not defined

In [31]:
a = 1

print(a) 

1


In [32]:
a = 1
a = 10
print(a) 

10


In [33]:
a = 1
b = a
a = 2
print(a,b)

2 1


In [34]:
studentID = 2013016032
# 이름을 나타내는 변수
student_name = "JeongSoo Na" 

In [35]:
a=1

In [36]:
b=1.2
c="Python"
d=True
e=None

In [37]:
print("a의 타입은 : ",type(a))
print("b의 타입은 : ",type(b))
print("c의 타입은 : ",type(c))
print("d의 타입은 : ",type(d))
print("e의 타입은 : ",type(e))

a의 타입은 :  <class 'int'>
b의 타입은 :  <class 'float'>
c의 타입은 :  <class 'str'>
d의 타입은 :  <class 'bool'>
e의 타입은 :  <class 'NoneType'>


In [38]:
a = 1 # 숫자형
b = "1" # 문자형

c = str(a) # 숫자 > 문자
d = int(b) # 문자 > 숫자 

In [40]:
a = [1,2,3,4,5] 

In [41]:
a = [1,1.2,"Hello",True, None]

In [42]:
a[0] 

1

In [43]:
a[2]

'Hello'

In [44]:
a[-2]

True

In [46]:
a[1] 

1.2

In [48]:
a[4]=7

In [49]:
a 

[1, 1.2, 'Hello', True, 7]

In [50]:
a[1:3] 

[1.2, 'Hello']

In [51]:
students = [[1,"짱구"],[2,"철수"],[3,"맹구"],[4,"유리"],[5,"훈이"]]

In [52]:
print(students[0])
print(students[1])
print(students[-1])

print(students[0][0])
print(students[0][1])
print(students[2][1])

[1, '짱구']
[2, '철수']
[5, '훈이']
1
짱구
맹구


In [56]:
del students[2] 
print(students) 

[[1, '짱구'], [2, '철수'], [4, '유리'], [5, '훈이']]


In [ ]:
a = (1,2,3,4)
a[1] 

In [57]:
del a[2]  

In [58]:
a = {1,2,4,5,1,3,2,4,5}
a

{1, 2, 3, 4, 5}

In [60]:
students = {\
    "id" : [1,2,3],\
    "name" : ["짱수","철수","유리"],\
    "favorite" : ["액션가면", "모에피", "토끼"]\
    }

In [110]:
a={"name":"BS","age":35,"sex":"female"}
a

{'name': 'BS', 'age': 35, 'sex': 'female'}

In [65]:
1+1

2

In [66]:
1*2

2

In [67]:
1/2 

0.5

In [68]:
x=1
y=2
x+y

3

In [69]:
3/5 

0.6

In [70]:
3%5

3

In [71]:
3//5

0

In [72]:
x**y

1

In [73]:
"a"+"b"

'ab'

In [74]:
"a"*3

'aaa'

In [75]:
a

{1, 2, 3, 4, 5}

In [76]:
a=0

In [79]:
a+1 

1

In [84]:
a+=1

In [85]:
a

2

In [86]:
a

2

In [87]:
a-1
if a>0:
    print("a는 양수입니다.") 

a는 양수입니다.


In [88]:
a-1
if a<0:
    print("a는 음수입니다.") 

In [89]:
a <0

False

In [93]:
a=1 
if a>0:
    print("a는 양수")
elif a<0:
    print("a는 음수")
else:
    print("a는 0")

a는 양수


In [98]:
a=0 
if a>0:
    print("a는 양수")
elif a<0:
    print("a는 음수")
else:
    print("a는 0")

a는 0


In [105]:
a=10
b=20
if a==10 and b==20:
    print("a는 10이고 b는 20이다.")

a는 10이고 b는 20이다.


In [106]:
a=10
b=10
if a==10 and b==20:
    print("a는 10이고 b는 20이다.")

In [107]:
a=10
b=10
if a==10 or b==20:
    print("a는 10이고 b는 20이다.")

a는 10이고 b는 20이다.


In [96]:
count = 0

while count == 10:
    print(count)
    count += 1

In [132]:
cnt=0

while True:
    print(cnt)
    cnt+=1
    if cnt==10:
         break

0
1
2
3
4
5
6
7
8
9


In [133]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [134]:
for i in [1,2,3,4,5]:
    print(i)

1
2
3
4
5


In [141]:
for i in["보선","세영","주한","지원"]:
    print(i)

보선
세영
주한
지원


In [135]:
for i in ["짱구","철수","유리","맹구","훈이"]:
    print(i)

짱구
철수
유리
맹구
훈이


In [145]:
for a in [1,2,3,4,5]:
    print(a)
    print("!!")
print("%%")    

1
!!
2
!!
3
!!
4
!!
5
!!
%%


In [146]:
for i in [1,2,3,4,5]:
    if i==3:
        continue
    print(i)

1
2
4
5


In [147]:
for i in [1,2,3,4,5]:
    if i==3:
        break
    print(i)

1
2


In [148]:
for i in range(0,10):
    print("i : " ,i)
    for j in [1,2,3,4,5]:
        print("j : ",j)

i :  0
j :  1
j :  2
j :  3
j :  4
j :  5
i :  1
j :  1
j :  2
j :  3
j :  4
j :  5
i :  2
j :  1
j :  2
j :  3
j :  4
j :  5
i :  3
j :  1
j :  2
j :  3
j :  4
j :  5
i :  4
j :  1
j :  2
j :  3
j :  4
j :  5
i :  5
j :  1
j :  2
j :  3
j :  4
j :  5
i :  6
j :  1
j :  2
j :  3
j :  4
j :  5
i :  7
j :  1
j :  2
j :  3
j :  4
j :  5
i :  8
j :  1
j :  2
j :  3
j :  4
j :  5
i :  9
j :  1
j :  2
j :  3
j :  4
j :  5


In [149]:
print("pen pineapple apple pen")
print("pen""pineapple""apple""pen")
print("pen","pineapple","apple","pen")
print("pen"+"pineapple"+"apple"+"pen")

print("pen")
print("pineapple")
print("apple")
print("pen")

print("pen", end=' ')
print("pineapple", end=' ')
print("apple", end=' ')
print("pen", end=' ')

print("pen", end='\n')
print("pineapple", end='\n')
print("apple", end='\n')
print("pen", end='\n')

pen pineapple apple pen
penpineappleapplepen
pen pineapple apple pen
penpineappleapplepen
pen
pineapple
apple
pen
pen pineapple apple pen pen
pineapple
apple
pen


In [150]:
def plus_one(a):
    # 함수 내부 기능
    result = a + 1
    # 반환값(Output)
    return result

plus_one(1)

2

In [151]:
plus_one(2)

3

In [157]:
plus_one(62)

63

In [165]:
a="Hello"
def plus_one(a):
    result = a + 1
    print(a)
    return result
print(a)
plus_one(1)

Hello
1


2

In [166]:
def solution(n):
    total=0
    for i in range(1,n+1):
        if i%2==0:
            total+=i
    return total

In [172]:
def solution(n):
    answer=0
    for i in range(n+1):
        if i%2==0:
            answer+=1
    return answer

In [174]:
solution(10)

6

In [154]:
def shouting():
    print("ah!!!!")

shouting()

ah!!!!


In [155]:
def function_1(a: str, b: int):
    print(a + "의 갯수는 " + str(b) + "개 입니다.")

function_1("사과",10)

사과의 갯수는 10개 입니다.


In [156]:
def function_2(a = "소주"):
    print(a + "한 병 주문이요")

In [177]:
class Count:
    def __init__(self):
        self.num = 0
    def increment(self):
        self.num += 1
        return self.num
cnt = Count()    

In [178]:
import os

file_list = os.listdir()
print(file_list)

['.git', '.ipynb_checkpoints', '0607파이썬실습', '250621', '250705', 'ARGV', 'class8-Python 클래스&모듈', 'kbs250607.ipynb', 'kbs250614.ipynb', 'README.md', 'test.py', 'Untitled.ipynb', 'Untitled1.ipynb']


In [179]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 '0607파이썬실습',
 '250621',
 '250705',
 'ARGV',
 'class8-Python 클래스&모듈',
 'kbs250607.ipynb',
 'kbs250614.ipynb',
 'README.md',
 'test.py',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [180]:
def hello():
    print("This is test.py")

# 입력받은 숫자가 짝수인가 홀수인가 확인
def function(num):
    result = ""
    if num % 2 == 0:
        result = "짝수"
    elif num % 2 == 1:
        result = "홀수"
    else:
        result = "입력받은 숫자가 정수가 아닙니다."
    return result

In [182]:
def solution(my_string):
    for i in ["a","e","i","o","u"]:
        my_string = my_string.replace(i,"")
    return my_string
solution("This is test.py")      

'Ths s tst.py'

In [ ]:
def solution(n, t):
    return n*(2**t)